Repository jenkinsci/google-compute-engine-plugin, pull requests merged in 2024-05, with the labels that each got.

#173 Minor UX changes
  src/main/resources/com/google/jenkins/plugins/computeengine/ComputeEngineComputer/configure.jelly
  src/main/resources/com/google/jenkins/plugins/computeengine/InstanceConfiguration/config.jelly
  src/main/resources/com/google/jenkins/plugins/computeengine/InstanceConfiguration/help-windowsConfiguration.html
Labels: enhancement

#456 replace gson library with gson-api plugin
  pom.xml
Labels: dependencies, developer

#458 do attempt to shade dependencies.
  pom.xml
Labels: developer

#465 Do not bundle eddsa library
  pom.xml
Labels: dependencies, developer
